/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppActionsCard: typeof import('./components/projects/AppActionsCard.vue')['default']
    AppConsoleCard: typeof import('./components/projects/AppConsoleCard.vue')['default']
    AppDatabaseCard: typeof import('./components/projects/AppDatabaseCard.vue')['default']
    AppDetailsCard: typeof import('./components/projects/AppDetailsCard.vue')['default']
    AppEnvVarsCard: typeof import('./components/projects/AppEnvVarsCard.vue')['default']
    AppLogsCard: typeof import('./components/projects/AppLogsCard.vue')['default']
    AppPreviewCard: typeof import('./components/projects/AppPreviewCard.vue')['default']
    Apps: typeof import('./components/projects/apps/index.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    DashboardComponent: typeof import('./components/dashboard/DashboardComponent.vue')['default']
    DocumentationComponent: typeof import('./components/documentation/DocumentationComponent.vue')['default']
    IconCloudDemo: typeof import('./components/demo/IconCloudDemo.vue')['default']
    InteractiveIconCloud: typeof import('./components/ui/InteractiveIconCloud.vue')['default']
    Login: typeof import('./components/login/index.vue')['default']
    LogViewer: typeof import('./components/logs/LogViewer.vue')['default']
    ProjectsComponent: typeof import('./components/projects/ProjectsComponent.vue')['default']
    RepoSelector: typeof import('./components/git/RepoSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingComponent: typeof import('./components/settings/SettingComponent.vue')['default']
  }
}
